### ISSUE TITLE
Maven Support

### ISSUE THREAD

**Issue by timo-reymann** [esoco/coroutines#1]
Currently i cant find the artifact on the maven central. Is maven support planned or currently wip?

**Comment by esocode** [comment]
The library is only published on JCenter, not on Maven Central. It should be sufficient to add JCenter to pom.xml, like shown below. That is the only repository needed because JCenter also includes all Maven Central dependencies. 
```xml
<repositories>
    <repository>
      <id>jcenter</id>
      <url>https://jcenter.bintray.com/</url>
    </repository>
</repositories>
```
I'm only using gradle so I have never tried this myself. Please let me know if that works for you. I'll then add that to the readme.

**Comment by timo-reymann** [comment]
Okay, thank you, it would be great if you add hint to the README :).

But please consider releasing it for the central repo too, e. g. in my company we have an mirror from the central and other repos can not be used due to network restrictions.

**Comment by esocode** [comment]
I looked into this but mirroring this to MavenCentral would a lot of additions to the build files of this project and it's dependencies because Maven Central needs a lot of information which JCenter handles implicitly. At the moment I don't have the time to modify all the projects and test the release cycle. But I'll keep this issue open as a reminder. But maybe you should look into using JCenter. It is a superset of Maven Central and there are several project that are only available on JCenter (because of the much simpler handling).

Another user came up with a Maven issue because it doesn't support the wildcard version resolution of Gradle, causing the download of the transitive dependencies to fail. The workaround is to include these dependencies directly into the pom.xml like this:
```xml
<dependencies>
    <dependency>
    <groupId>de.esoco</groupId>
    <artifactId>coroutines</artifactId>
    <version>0.9.0</version>
    </dependency>
    <dependency>
    <groupId>org.obrel</groupId>
    <artifactId>objectrelations</artifactId>
    <version>1.3.0</version>
    </dependency>
    <dependency>
    <groupId>de.esoco</groupId>
    <artifactId>esoco-common</artifactId>
    <version>1.2.0</version>
    </dependency>
</dependencies>
```

**Comment by timo-reymann** [comment]
Okay thank you, cant test it right now, but i will try it and give some feedback. 
I just submitted a PR for a cleaner README :)

Great work btw :+1:
